version: "2"
services:
    www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        volumes:
            - ./initdb:/docker-entrypoint-initdb.d
            #- persistent:/var/lib/mysql
        networks:
            - default
